spring:
  application.name: home-spring-boot
  profiles:
    active: PROD

server:
  port: 9980

logging:
  level:
    root: DEBUG
  pattern:
    console: "%d{DEFAULT} [%thread] %-5level %logger{36} - %msg%n"

inspect: true

common:
  destination: "registered service..."
